name: gatekeeper_kerchanshe
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

  charts_flutter: ^0.9.0
  http: ^0.12.2
  intl:
  device_info: ^1.0.0
  path_provider: any
  percent_indicator: "^2.1.7+2"
  pin_code_fields: ^6.0.1
  shared_preferences: ^0.5.12+4
  sliding_switch: ^0.0.3
  sqflite: ^1.3.2+1
  toggle_switch: ^0.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/assets/k.png
    - lib/assets/big_k.png
    - lib/assets/login_bg.png
    - lib/assets/pin.png
    - lib/assets/power_icon.png
    - lib/assets/images/splash.png
    - lib/assets/listing_bg.png
    - lib/assets/greenicon.png
    - lib/assets/truck.png
    - lib/assets/tick.png
    - lib/assets/key.png
    - lib/assets/green_bg.png
    - lib/assets/white_bg.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Catamaran-Bold
      fonts:
        - asset: lib/fonts/Catamaran-Bold.ttf

    - family: Catamaran-Light
      fonts:
        - asset: lib/fonts/Catamaran-Light.ttf

    - family: Catamaran-Medium
      fonts:
        - asset: lib/fonts/Catamaran-Medium.ttf

    - family: Catamaran-Regular
      fonts:
        - asset: lib/fonts/Catamaran-Regular.ttf

    - family: Catamaran-Thin
      fonts:
        - asset: lib/fonts/Catamaran-Thin.ttf

    - family: Lato-Bold
      fonts:
        - asset: lib/fonts/Lato-Bold.ttf

    - family: Lato-Light
      fonts:
        - asset: lib/fonts/Lato-Light.ttf

    - family: Lato-Regular
      fonts:
        - asset: lib/fonts/Lato-Regular.ttf

    - family: Lato-Thin
      fonts:
        - asset: lib/fonts/Lato-Thin.ttf

    - family: Montserrat-Thin
      fonts:
        - asset: lib/fonts/Montserrat-Thin.ttf

    - family: Montserrat-Regular
      fonts:
        - asset: lib/fonts/Montserrat-Regular.ttf

    - family: Montserrat-Medium
      fonts:
        - asset: lib/fonts/Montserrat-Medium.ttf

    - family: Montserrat-Light
      fonts:
        - asset: lib/fonts/Montserrat-Light.ttf

    - family: Montserrat-Bold
      fonts:
        - asset: lib/fonts/Montserrat-Bold.ttf

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
